version: '3.9'

services:
  db:
    container_name: aierview-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aierview
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aierview-network

volumes:
  pgdata:

networks:
  aierview-network:
    driver: bridge

