# fly.homolog.toml app configuration file generated for api-aierview-homolog on 2025-08-05T02:47:20-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-aierview-homolog'
primary_region = 'gig'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '4gb'
cpu_kind = 'shared'
cpus = 2
