google:
  token-info-url: ${GOOGLE_TOKEN_INFO_URL}

r2:
  endpoint: ${R2_ENDPOINT}
  bucket: ${R2_BUCKET}
  access_key: ${R2_ACCESS_KEY}
  secret_key: ${R2_SECRET_KEY}
  audio_file_path: ${R2_AUDIO_FILE_PATH}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: ${JWT_EXPIRATION_TIME}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.aierview.backend.interview.domain.model.InterviewEventConsumerPayload