-- Create table t_users
CREATE TABLE t_users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255),
    name  VARCHAR(255),
    role  VARCHAR(50) CHECK (role IN ('MOBILE', 'FRONTEND', 'BACKEND', 'FULLSTACK')),
    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- Create table t_auth
CREATE TABLE t_auth
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    password VARCHAR(255),
    picture  VARCHAR(255),
    provider VARCHAR(50) CHECK (provider IN ('LOCAL', 'GOOGLE')),
    user_id  BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_auth_user_id UNIQUE (user_id),
    CONSTRAINT fk_auth_user_id FOREIGN KEY (user_id) REFERENCES t_users (id)
);
